package dev.yycodes.paymentsimulator.audit;

public enum PayoutEventType {
    PROCESSING_STARTED,
    PROVIDER_SUCCEEDED,
    PROVIDER_DECLINED,
    PROVIDER_TIMEOUT,
    PROVIDER_RETRY_SUCCEEDED,
    PROVIDER_RETRY_DECLINED,
    PROVIDER_RETRY_TIMEOUT,
    RECONCILIATION_SUCCEEDED,
    RECONCILIATION_FAILED
}
